[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "UnrealDrive"
authors = [{name = "Ivan Zhukov", email = "ivzhuk7@gmail.com"}]
dynamic = ["version", "description"]
